name: Code styling
on:
  #pull_request:
  #  branches:
  #    - main
  workflow_dispatch:
 #  schedule:
 #    - cron: "0 0 15 1/3 *" # 15th of every 3rd month, for now


concurrency:
  # only one run per branch at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  setup-module-matrix:
    runs-on: ubuntu-latest
    name: Setup the module matrix
    outputs:
      module: ${{ steps.read-modules.outputs.module }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read analysis modules
        id: read-modules
        run: |
          # From input `mature-modules.json`, read in modules which should be styled and save to $GITHUB_OUTPUT
          #echo jq -c . < ".github/workflows/mature-modules.json" > $GITHUB_OUTPUT
          echo "module=$(jq -cr . < ./.github/workflows/mature-modules.json)" > $GITHUB_OUTPUT


  print-it:
    runs-on: ubuntu-latest
    name: print baby
    needs: setup-module-matrix
    strategy:
      matrix:
        usernames: ${{ fromJSON(needs.setup-module-matrix.outputs.module) }}

    steps:
      - name: print it
        run: |
          echo "${{ matrix.module }}"
